<?php
$pageTitle = 'List a Space';
require_once __DIR__ . '/includes/header.php';
require_once __DIR__ . '/includes/sidebar.php';
$db=Database::getInstance(); $userId=(int)$currentUser['id'];
$hideTopbarSearch = true;
$categories=$db->query('SELECT id,name FROM categories WHERE is_active=1 ORDER BY name')->fetchAll();
$amenities=$db->query('SELECT id,name FROM amenities ORDER BY name')->fetchAll(); $errors=[];
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['submit_listing'])){
 $d=['category'=>(int)($_POST['category_id']??0),'title'=>trim($_POST['title']??''),'description'=>trim($_POST['description']??''),'address'=>trim($_POST['address']??''),'city'=>trim($_POST['city']??''),'state'=>trim($_POST['state']??''),'zip'=>trim($_POST['zip_code']??''),'size'=>(int)($_POST['total_sqft']??0),'capacity'=>(int)($_POST['max_capacity']??0),'daily'=>$_POST['daily_rate']??''];
 if(!$d['category']||!$d['title']||!$d['description']||!$d['address']||!$d['city']||!$d['state']||!$d['zip'])$errors[]='Please complete all required listing and location details.';
 if($d['size']<1||$d['capacity']<1)$errors[]='Enter a valid size and capacity.'; if(!is_numeric($d['daily'])||(float)$d['daily']<=0)$errors[]='Enter a valid daily rate.';
 if(!$errors){try{$db->beginTransaction();$q=$db->prepare("INSERT INTO spaces(owner_id,category_id,title,description,address,city,state,zip_code,total_sqft,max_capacity,daily_rate,weekly_rate,monthly_rate,security_deposit,verification_status,is_active) VALUES(:o,:c,:t,:d,:a,:city,:st,:z,:sq,:cap,:rate,:week,:month,:deposit,'pending',1)");$q->execute([':o'=>$userId,':c'=>$d['category'],':t'=>$d['title'],':d'=>$d['description'],':a'=>$d['address'],':city'=>$d['city'],':st'=>$d['state'],':z'=>$d['zip'],':sq'=>$d['size'],':cap'=>$d['capacity'],':rate'=>$d['daily'],':week'=>($_POST['weekly_rate']?:null),':month'=>($_POST['monthly_rate']?:null),':deposit'=>($_POST['security_deposit']?:0)]);$id=(int)$db->lastInsertId();$ai=$db->prepare('INSERT INTO space_amenities(space_id,amenity_id) VALUES(:s,:a)');foreach(array_unique(array_map('intval',$_POST['amenities']??[]))as$a)$ai->execute([':s'=>$id,':a'=>$a]);$pi=$db->prepare('INSERT INTO space_purposes(space_id,purpose_name) VALUES(:s,:p)');foreach(array_unique(array_filter($_POST['purposes']??[]))as$p)$pi->execute([':s'=>$id,':p'=>substr($p,0,100)]);$imageInsert=$db->prepare('INSERT INTO space_images(space_id,image_path,is_primary) VALUES(:space,:path,:primary)');$uploadDir=null;$savedImageCount=0;foreach($_FILES['photos']['tmp_name']??[]as$index=>$tmp){if(($_FILES['photos']['error'][$index]??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)continue;if(($_FILES['photos']['error'][$index]??UPLOAD_ERR_OK)!==UPLOAD_ERR_OK)throw new RuntimeException('One of the selected photos could not be uploaded. Please choose it again.');if(($_FILES['photos']['size'][$index]??0)>35*1024*1024)throw new RuntimeException('Each photo must be 35 MB or smaller.');if(!is_uploaded_file($tmp))throw new RuntimeException('The selected photo was not received by the server. Please choose it again.');$extension=strtolower(pathinfo($_FILES['photos']['name'][$index],PATHINFO_EXTENSION));if(!in_array($extension,['jpg','jpeg','png','webp'],true))throw new RuntimeException('Only JPG, PNG, and WebP images are allowed.');if($uploadDir===null){$uploadDir=__DIR__.'/../assets/uploads/spaces';if(!is_dir($uploadDir)&&!mkdir($uploadDir,0775,true))throw new RuntimeException('Upload folder cannot be created.');}$filename='space-'.bin2hex(random_bytes(12)).'.'.$extension;if(!move_uploaded_file($tmp,$uploadDir.'/'.$filename))throw new RuntimeException('Could not save an uploaded photo.');$imageInsert->execute([':space'=>$id,':path'=>'assets/uploads/spaces/'.$filename,':primary'=>$savedImageCount===0?1:0]);$savedImageCount++;}$db->commit();$_SESSION['flash_success']='Your listing was submitted for review.';header('Location: '.APP_URL.'/user/my-spaces.php');exit;}catch(Throwable $e){error_log('List-space submission failed: '.$e->getMessage());if($db->inTransaction())$db->rollBack();$errors[]=$e instanceof RuntimeException?$e->getMessage():'Could not save your listing. Please try again.';}}
}
$unreadNotifCount=0;$steps=['Basic Info','Location','Capacity','Pricing','Availability','Amenities','Photos','Rules','Review'];
?>
<div id="user-main"><?php require_once __DIR__.'/includes/topbar.php'; ?>
<div class="listing-progress"><?php foreach($steps as$i=>$s):?><span class="listing-step" data-step="<?=++$i?>"><b><?=$i?></b><?=$s?></span><?php if($i<9):?><i></i><?php endif;endforeach?></div>
<main id="user-content" class="listing-page"><?php if($errors):?><div class="bp-alert error"><?=htmlspecialchars(implode(' ',$errors))?></div><?php endif?><form method="post" enctype="multipart/form-data" id="listingForm"><input type="hidden" name="submit_listing" value="1">
<?php for($step=1;$step<=9;$step++):?><section class="listing-panel" data-panel="<?=$step?>"><h1>Step <?=$step?>: <?=$steps[$step-1]?></h1><p class="listing-subtitle"><?=$step===9?'Review everything before submitting.':'Fill in the required details below.'?></p><div class="listing-card">
<?php if($step===1):?><label>Space title *<input required id="title" name="title" placeholder="e.g. The Studio at Versova"></label><label>Space type *<select required id="category" name="category_id"><option value="">Select type</option><?php foreach($categories as$c):?><option value="<?=$c['id']?>"><?=htmlspecialchars($c['name'])?></option><?php endforeach?></select></label><label>Description *<textarea required id="description" name="description" placeholder="Describe your space — what makes it unique, suitable uses, special features..."></textarea></label>
<?php elseif($step===2):?><label>Full address *<input required id="address" name="address" placeholder="Building name, street address"></label><div class="listing-grid"><label>City *<input required id="city" name="city" placeholder="e.g. Mumbai"></label><label>State *<input required id="state" name="state" placeholder="e.g. Maharashtra"></label></div><div class="listing-grid"><label>Area / Locality<input name="locality" placeholder="e.g. Bandra West"></label><label>PIN code *<input required id="zip" name="zip_code" placeholder="400050"></label></div>
<?php elseif($step===3):?><div class="listing-grid"><label>Capacity (persons) *<input required type="number" min="1" id="capacity" name="max_capacity" placeholder="20"></label><label>Size (sq ft) *<input required type="number" min="1" id="size" name="total_sqft" placeholder="e.g. 1,200"></label></div><span class="listing-label">Suitable uses</span><div class="listing-check-grid"><?php foreach(['Meetings','Events','Photography','Workshops','Training','Co-working','Productions','Exhibitions','Wheelchair accessible']as$p):?><label class="check-label"><input type="checkbox" name="purposes[]" value="<?=$p?>"><?=$p?></label><?php endforeach?></div>
<?php elseif($step===4):?><div class="listing-grid"><label>Daily rate (₹) *<input required id="daily" type="number" min="1" name="daily_rate" placeholder="1500"></label><label>Weekly rate (₹)<input type="number" min="0" name="weekly_rate" placeholder="Optional"></label></div><div class="listing-grid"><label>Monthly rate (₹)<input type="number" min="0" name="monthly_rate" placeholder="Optional"></label><label>Security deposit (₹)<input type="number" min="0" name="security_deposit" placeholder="0"></label></div><label>Additional pricing notes<textarea name="pricing_notes" placeholder="e.g. Weekend surcharge applies..."></textarea></label>
<?php elseif($step===5):?><span class="listing-label">Available days</span><div class="day-picker"><?php foreach(['Mon','Tue','Wed','Thu','Fri','Sat','Sun']as$day):?><label><input type="checkbox" name="days[]" value="<?=$day?>" <?=in_array($day,['Mon','Tue','Wed','Thu','Fri'])?'checked':''?>><span><?=$day?></span></label><?php endforeach?></div><div class="listing-grid"><label>Available from<input type="time" name="available_from" value="09:00"></label><label>Available until<input type="time" name="available_until" value="21:00"></label></div><label>Advance booking required<select name="advance_booking"><option>No minimum</option><option>1 day</option><option>2 days</option></select></label><p class="field-hint">Recurring availability is not yet persisted by the database.</p>
<?php elseif($step===6):?><p class="listing-label">Select all amenities available at your space.</p><div class="listing-check-grid"><?php foreach($amenities as$a):?><label class="check-label"><input type="checkbox" name="amenities[]" value="<?=$a['id']?>"><?=htmlspecialchars($a['name'])?></label><?php endforeach?></div>
<?php elseif($step===7):?><div class="photo-drop"><i class="bi bi-upload"></i><strong>Upload photos</strong><p>JPG, PNG or WebP · up to 35 MB each</p><label class="photo-choose" for="listingPhotos">Choose files</label><input class="photo-input" id="listingPhotos" type="file" name="photos[]" accept="image/jpeg,image/png,image/webp" multiple><div id="photoNames" class="photo-names"></div></div><p class="field-hint">The first photo will be used as the primary listing image.</p>
<?php elseif($step===8):?><label>Space rules<textarea name="rules" placeholder="List rules one per line, e.g.&#10;No smoking&#10;Remove footwear at entrance"></textarea></label><label>Booking requirements<textarea name="requirements" placeholder="e.g. Government ID required, security deposit..."></textarea></label><span class="listing-label">Restrictions</span><div class="listing-check-grid"><?php foreach(['No alcohol','No smoking','No pets','No minors unaccompanied','No late-night use']as$r):?><label class="check-label"><input type="checkbox" name="restrictions[]" value="<?=$r?>"><?=$r?></label><?php endforeach?></div><p class="field-hint">Rules need dedicated database fields before publication.</p>
<?php else:?><div class="listing-review" id="listingReview"></div><div class="listing-warning"><strong>Your listing will be reviewed before publishing</strong><p>After submission, the AVASTRA team will verify your listing details. This usually takes 1–2 business days.</p></div><?php endif?></div>
<div class="listing-actions"><?php if($step===1):?><a class="btn btn-ghost-avastra" href="<?=APP_URL?>/user/dashboard.php"><i class="bi bi-arrow-left"></i> Cancel</a><?php else:?><button type="button" class="btn btn-ghost-avastra" onclick="go(<?=$step-1?>)"><i class="bi bi-arrow-left"></i> Previous</button><?php endif?><?php if($step<9):?><button type="button" class="btn btn-primary-avastra" onclick="go(<?=$step+1?>)">Continue <i class="bi bi-arrow-right"></i></button><?php else:?><button class="btn btn-primary-avastra">Submit for Review</button><?php endif?></div></section><?php endfor?></form></main><?php require_once __DIR__.'/includes/footer.php';?>
<script>let current=1,required={1:['title','category','description'],2:['address','city','state','zip'],3:['capacity','size'],4:['daily']};function draw(){document.querySelectorAll('.listing-panel').forEach(x=>x.classList.toggle('active',+x.dataset.panel===current));document.querySelectorAll('.listing-step').forEach(x=>{let n=+x.dataset.step;x.classList.toggle('active',n===current);x.classList.toggle('done',n<current);x.querySelector('b').textContent=n<current?'✓':n});if(current===9)review();scrollTo({top:0,behavior:'smooth'})}function go(to){if(to>current&&required[current]){let ok=true;required[current].forEach(id=>{let e=document.getElementById(id);if(!e.value.trim()){e.classList.add('invalid');ok=false}else e.classList.remove('invalid')});if(!ok)return}current=to;draw()}function review(){let v=id=>document.getElementById(id)?.value.trim()||'—';document.getElementById('listingReview').innerHTML=[['Basic information provided',v('title')],['Location set',v('address')+', '+v('city')],['Capacity configured',v('capacity')+' people · '+v('size')+' sq ft'],['Pricing configured','₹'+v('daily')+' per day'],['Amenities selected',document.querySelectorAll('input[name="amenities[]"]:checked').length+' selected']].map(x=>`<div><i class="bi bi-check-lg"></i><span>${x[0]}<small>${x[1]}</small></span></div>`).join('')}document.getElementById('listingPhotos').addEventListener('change',e=>{document.getElementById('photoNames').textContent=[...e.target.files].map(f=>f.name).join(' · ')});draw()</script>
